repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.3
    hooks:
      # Run the linter.
      - id: ruff
        # args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        language: system
        types: [python]
        entry: uv run pytest
        pass_filenames: false
        always_run: true
